version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-28
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx1024m"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=8"
      TERM: dumb
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - run:
          name: Run JVM Tests & Lint
          command: ./gradlew check
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results


